### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/crm#14]
**Environment:**
Windows
Chrome

**Detailed Description**
When attempting to add contributions to the CRM users receive an error message when hitting save. 

**To Reproduce**
Enter a contribution and hit save or literally just hit save without first doing anything else.

**Screenshots**
![image](https://user-images.githubusercontent.com/30630157/55838703-55876480-5af3-11e9-9d6d-c5dd266d2a70.png)

**Comment by codygordon** [comment]
Should be fixed!
